[tool.poetry]
name = "env-curs"
description = "env curs analiza datelor complexe"
version = "0.1.0"
authors = [ "Andrei Berinde" ]
readme = "README.md"
repository = "https://github.com/berinde/curs-analiza-datelor-complexe"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
matplotlib = "^3.7.0"
contractions = "^0.0.55"
nltk = "^3.6.5"
spacy = "^3.6.1"
pandas = "^2.0.0"
numpy = "^1.24.1"
wordcloud = "^1.8.2.2"
scikit-learn = "^1.2.1"
gensim = "^4.3.0"
plotly = "^5.12.0"
textblob = "^0.15.3"
tensorflow = "2.11.0"
pyLDAvis = "^3.3.1"
ktrain = "0.32.2"
transformers = "^4.17.0"
nrclex = "^2.0.2"
afinn = "0.1"
ipykernel = "^6.19.1"
xgboost = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
